import StyleDictionary from "style-dictionary";
import { toCamelCase, transformValue } from "./helpers.js";

// Register combined-swiftui-uikit-color-format for primitive colors
StyleDictionary.registerFormat({
  name: "combined-swiftui-uikit-color-format",
  formatter: function ({ dictionary, file, options }) {
    console.log(`Generating brand colors for ${file.destination}`);

    const brandName = file.destination
      .split("/")
      .pop()
      .replace("Colors.swift", ""); // Extract brand name from the file path

    // Generate SwiftUI and UIKit colors based on the brand's primitive colors
    const swiftUIColorBlock = dictionary.allProperties
      .map((token) => {
        const nameParts = token.path.filter(
          (part) => part.toLowerCase() !== "color"
        );
        const name = nameParts.join("").replace(/-/g, ""); // Remove dashes and combine

        return `    static let ${name} = Color(hex: "${token.value}")`;
      })
      .join("\n");

    const uiColorBlock = dictionary.allProperties
      .map((token) => {
        const nameParts = token.path.filter(
          (part) => part.toLowerCase() !== "color"
        );
        const name = nameParts.join("").replace(/-/g, ""); // Remove dashes and combine

        return `    static let ${name} = UIColor(hex: "${token.value}")`;
      })
      .join("\n");

    return `import SwiftUI
  
  // Generated by https://github.com/warp-ds/tokens
  struct ${brandName}Colors {
  ${swiftUIColorBlock}
  }
  
  struct ${brandName}UIColors {
  ${uiColorBlock}
  }
  `;
  },
});

// Register token-provider-swift-format for iOS TokenProvider generation
StyleDictionary.registerFormat({
  name: "token-provider-swift-format",
  formatter: function ({ dictionary, file, options }) {
    console.log(
      `Inside token-provider-swift-format formatter for ${file.destination}`
    );

    const brandName = file.destination
      .split("/")
      .pop()
      .replace("Tokens.swift", ""); // Extract brand name from the file path

    // Generate SwiftUI light colors
    const swiftUIColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep semantic tokens
      .map((token) => {
        let name = toCamelCase(token.path.slice(2).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts

        return `    var ${name}: Color { get }`;
      })
      .join("\n");

    // Generate UIKit light colors
    const uiColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep semantic tokens
      .map((token) => {
        let name = toCamelCase(token.path.slice(2).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts

        return `    var ${name}: UIColor { get }`;
      })
      .join("\n");

    return `import SwiftUI
  
  // Generated by https://github.com/warp-ds/tokens
  public protocol TokenProvider {
  ${swiftUIColorBlock}
  }
  
  public protocol UITokenProvider {
  ${uiColorBlock}
  }
  `;
  },
});

// Register tokens-light-swift-format for iOS light token generation
StyleDictionary.registerFormat({
  name: "tokens-light-swift-format",
  formatter: function ({ dictionary, file, options }) {
    console.log(
      `Inside tokens-light-swift-format formatter for ${file.destination}`
    );

    const brandName = file.destination
      .split("/")
      .pop()
      .replace("Tokens.swift", ""); // Extract brand name from the file path

    // Generate SwiftUI light colors
    const swiftUIColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep semantic tokens
      .map((token) => {
        let name = toCamelCase(token.path.slice(2).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    public var ${name}: Color { ${brandName.replace(
          "Light",
          ""
        )}${value} }`;
      })
      .join("\n");

    // Generate UIKit light colors
    const uiColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep semantic tokens
      .map((token) => {
        let name = toCamelCase(token.path.slice(2).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    public var ${name}: UIColor { ${brandName.replace(
          "Light",
          ""
        )}UI${value} }`;
      })
      .join("\n");

    return `import SwiftUI
  
  // Generated by https://github.com/warp-ds/tokens
  struct ${brandName}TokenProvider: TokenProvider {
  ${swiftUIColorBlock}
  }
  
  struct ${brandName}UITokenProvider: UITokenProvider {
  ${uiColorBlock}
  }`;
  },
});

// Register tokens-dark-swift-format for iOS dark token generation
StyleDictionary.registerFormat({
  name: "tokens-dark-swift-format",
  formatter: function ({ dictionary, file, options }) {
    console.log(
      `Inside tokens-dark-swift-format formatter for ${file.destination}`
    );

    const brandName = file.destination
      .split("/")
      .pop()
      .replace("Tokens.swift", ""); // Extract brand name from the file path

    // Generate SwiftUI dark colors
    const swiftUIColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep semantic tokens
      .map((token) => {
        let name = toCamelCase(token.path.slice(2).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    public var ${name}: Color { ${brandName.replace(
          "Dark",
          ""
        )}${value} }`;
      })
      .join("\n");

    // Generate UIKit dark colors
    const uiColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep semantic tokens
      .map((token) => {
        let name = toCamelCase(token.path.slice(2).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    public var ${name}: UIColor { ${brandName.replace(
          "Dark",
          ""
        )}UI${value} }`;
      })
      .join("\n");

    return `import SwiftUI
  
  // Generated by https://github.com/warp-ds/tokens
  struct ${brandName}TokenProvider: TokenProvider {
  ${swiftUIColorBlock}
  }
  
  struct ${brandName}UITokenProvider: UITokenProvider {
  ${uiColorBlock}
  }`;
  },
});

// Register colors-light-swift-format for iOS light color generation
StyleDictionary.registerFormat({
  name: "colors-light-swift-format",
  formatter: function ({ dictionary, file, options }) {
    console.log(
      `Inside colors-light-swift-format formatter for ${file.destination}`
    );

    const brandName = file.destination
      .split("/")
      .pop()
      .replace("Colors.swift", ""); // Extract brand name from the file path

    // Generate SwiftUI light colors
    const swiftUIColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep component colors
      .filter((token) => !token.path[1].startsWith("color")) // Exclude semantic tokens, only keep component colors
      .map((token) => {
        let name = toCamelCase(token.path.slice(1).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    var ${name}: Color { ${brandName.replace(
          "Light",
          ""
        )}${value} }`;
      })
      .join("\n");

    // Generate UIKit light colors
    const uiColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep component colors
      .filter((token) => !token.path[1].startsWith("color")) // Exclude semantic tokens, only keep component colors
      .map((token) => {
        let name = toCamelCase(token.path.slice(1).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    var ${name}: UIColor { ${brandName.replace(
          "Light",
          ""
        )}UI${value} }`;
      })
      .join("\n");

    return `import SwiftUI
  
  // Generated by https://github.com/warp-ds/tokens
  struct ${brandName}ColorProvider {
  ${swiftUIColorBlock}
  }
  
  struct ${brandName}UIColorProvider {
  ${uiColorBlock}
  }`;
  },
});

// Register colors-dark-swift-format for iOS dark color generation
StyleDictionary.registerFormat({
  name: "colors-dark-swift-format",
  formatter: function ({ dictionary, file, options }) {
    console.log(
      `Inside colors-dark-swift-format formatter for ${file.destination}`
    );

    const brandName = file.destination
      .split("/")
      .pop()
      .replace("Colors.swift", ""); // Extract brand name from the file path

    // Generate SwiftUI dark colors
    const swiftUIColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep component colors
      .filter((token) => !token.path[1].startsWith("color")) // Exclude semantic tokens, only keep component colors
      .map((token) => {
        let name = toCamelCase(token.path.slice(1).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    var ${name}: Color { ${brandName.replace(
          "Dark",
          ""
        )}${value} }`;
      })
      .join("\n");

    // Generate UIKit dark colors
    const uiColorBlock = dictionary.allProperties
      .filter((token) => !token.path[0].startsWith("color")) // Exclude primitive colors, only keep component colors
      .filter((token) => !token.path[1].startsWith("color")) // Exclude semantic tokens, only keep component colors
      .map((token) => {
        let name = toCamelCase(token.path.slice(1).join("-")).replace(
          "Default",
          ""
        ); // Convert to camelCase, removing first two parts
        let value = transformValue(token.original.value);

        return `    var ${name}: UIColor { ${brandName.replace(
          "Dark",
          ""
        )}UI${value} }`;
      })
      .join("\n");

    return `import SwiftUI
  
  // Generated by https://github.com/warp-ds/tokens
  struct ${brandName}ColorProvider {
  ${swiftUIColorBlock}
  }
  
  struct ${brandName}UIColorProvider {
  ${uiColorBlock}
  }`;
  },
});
