---
name: Fetch from Figma
on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true
      - name: create env file
        run: |
          touch .env
          echo FIGMA_TOKEN=${{ secrets.FIGMA_TOKEN }} >> .env
      - name: Build
        run: pnpm build
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: timestamp
          commit-message: Updates from figma
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          title: 'Updates from figma'
          body: |
            Updates fetched from Figma
            - Check diff under tokens folder to see what's changed
          team-reviewers: warp-ds/warp-core-team