---
name: Release
on:
  push:
    branches:
    - master
    - alpha
    - next
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true
      - name: Build
        run: pnpm build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: Eik login and publish
        run: pnpm eik login -k $EIK_TOKEN && pnpm eik publish || true
        env:
          EIK_TOKEN: ${{ secrets.EIK_TOKEN }}